---
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
repos:
    - repo: "https://github.com/commitizen-tools/commitizen"
      rev: 3.12.0 # automatically updated by Commitizen
      hooks:
          - id: commitizen
          - id: commitizen-branch
            stages:
                - post-commit
                - push

    - repo: "https://github.com/pre-commit/pre-commit-hooks"
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
            exclude: '\{\{.*'
          - id: check-builtin-literals
            exclude: '\{\{.*'
          - id: check-case-conflict
          - id: check-docstring-first
            exclude: '\{\{.*'
          - id: check-json
            exclude: '\{\{.*'
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-toml
            exclude: '\{\{.*'
          - id: check-vcs-permalinks
          - id: check-xml
            exclude: '\{\{.*'
          - id: debug-statements
            exclude: '\{\{.*'
          - id: detect-private-key
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            exclude: '\{\{.*'
          - id: trailing-whitespace
            types: [python]
            exclude: '\{\{.*'
            args: [--markdown-linebreak-ext=md]
          - id: end-of-file-fixer
            types: [python]
            exclude: '\{\{.*'

    - repo: "https://github.com/adrienverge/yamllint.git"
      rev: v1.33.0
      hooks:
          - id: yamllint
            exclude: '^\{\{.*'
            files: \.(yaml|yml)$
            entry: yamllint --strict --config-file .yamllint.yml

    - repo: local
      hooks:
          # This calls a custom pre-commit script.
          # Disable if you don't have it.
          - id: stopwords
            name: stopwords
            entry: git-stopwords
            # args: ["-v"]
            language: system
            pass_filenames: true
            types: [text]

          - id: shellcheck
            name: shellcheck
            entry: shellcheck --check-sourced -e SC1009 -e SC1054 -e SC1073 -e SC1083 -e SC1056 -e SC1072
            language: system
            types: [shell]

          - id: poetry-check
            name: poetry check
            entry: poetry check
            language: system
            files: pyproject.toml
            pass_filenames: false
