---
name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"

outputs:
  python-version:
    description: The installed python version. Useful when given a version range as input.
    value: ${{ '{{' }} steps.setup-python.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Setup uv with cache
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ '{{' }} matrix.python-version }}
      shell: bash
      run: uv python install ${{ '{{' }} matrix.python-version }}

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev

    - name: Minimize uv cache
      shell: bash
      run: uv cache prune --ci
