---
name: "Test Cookiecutter"

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "*.md"
            - "*.yaml"
            - "*.yml"
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths-ignore:
            - "*.md"
            - "*.yaml"
            - "*.yml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-cookiecutter:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                # python-version: ["3.10", "3.11", "3.12"]
                python-version: ["3.10"]
        name: Python ${{ matrix.python-version }}

        steps:
            # ----------------------------------------------
            #    Install python and checkout repository
            # ----------------------------------------------
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Checkout
              uses: actions/checkout@v4

            # ----------------------------------------------
            #    Install poetry and project dependencies
            # ----------------------------------------------

            - name: Setup Python and Poetry
              uses: ./.github/actions/setup-poetry

            - name: Install dependencies
              run: poetry install

            # ----------------------------------------------
            #    Install poetry and project dependencies
            # ----------------------------------------------

            - name: Run cookiecutter create
              shell: bash
              run: |
                  poetry run cookiecutter --no-input . python_version="${{ matrix.python-version }}" package_name="ci_package"
                  cd ci-package
                  echo "-----------> poetry info <-----------"
                  poetry env info
                  echo "-----------> poetry install <-----------"
                  poetry install
                  echo "-----------> activate virtualenv <-----------"
                  poetry env use ${PWD}/.venv/bin/python
                  echo "-----------> poetry info <-----------"
                  poetry env info
                  echo "-----------> copy config file so tests pass <-----------"
                  mkdir -p /home/runner/.config/ci-package
                  cp src/ci_package/default_config.toml /home/runner/.config/ci-package/config.toml

            # ----------------------------------------------
            #    copy config file to runner so tests will pass
            # ----------------------------------------------
            # - name: Create empty configuration file
            #   shell: bash
            #   run: |
            #       echo "PWD: ${PWD}"
            #       mkdir -p /home/runner/.config/ci-package
            #       cp /home/runner/work/cookiecutter-python/cookiecutter-python/ci-package/src/ci_package/default_config.toml /home/runner/.config/ci-package/config.toml

            # ----------------------------------------------
            #    Test installed package
            # ----------------------------------------------
            - name: Test `cli --version`
              shell: bash
              run: |
                  poetry env use ${PWD}/ci-package/.venv/bin/python
                  poetry run ci-package --version

            - name: Run tests
              shell: bash
              run: |
                  poetry env use ${PWD}/ci-package/.venv/bin/python
                  poetry run pytest tests/
