---
name: "Test Cookiecutter"

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "*.md"
            - "*.yaml"
            - "*.yml"
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths-ignore:
            - "*.md"
            - "*.yaml"
            - "*.yml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-cookiecutter:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        name: Python ${{ matrix.python-version }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # ----------------------------------------------
            #    Install python, poetry and project dependencies
            # ----------------------------------------------

            - name: Setup Python and Poetry
              uses: ./.github/actions/setup-poetry

            # ----------------------------------------------
            #    Install poetry and project dependencies
            # ----------------------------------------------

            - name: Run cookiecutter create
              shell: bash
              run: |
                  poetry run cookiecutter -v --no-input . python_version="${{ matrix.python-version }}" package_name="cipackage"
                  cd cipackage
                  echo "\n-----------> poetry install <-----------\n"
                  poetry install
                  echo "\n-----------> activate virtualenv <-----------\n"
                  poetry env use ${PWD}/.venv/bin/python
                  echo "\n-----------> copy config file so tests pass <-----------\n"
                  mkdir -p /home/runner/.config/cipackage
                  cp src/cipackage/default_config.toml /home/runner/.config/cipackage/config.toml
                  echo "\n----------->run 'cli --version' <-----------\n"
                  poetry run cipackage --version
                  echo "\n----------->run pytests <-----------\n"
                  poetry run pytest tests/
